server:
  port: 8001


eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8003/eureka/"
      
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

resilience4j.circuitbreaker:
    instances:
        schoolService:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: count_based
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10

         
            
#resilience4j.retry:
#    instances:
#        backendA:
#            maxAttempts: 3
#            waitDuration: 10s
#            enableExponentialBackoff: true
#            exponentialBackoffMultiplier: 2
#            retryExceptions:
#                - org.springframework.web.client.HttpServerErrorException
#                - java.io.IOException
#            ignoreExceptions:
#                - io.github.robwin.exception.BusinessException
#        backendB:
#            maxAttempts: 3
#            waitDuration: 10s
#            retryExceptions:
#                - org.springframework.web.client.HttpServerErrorException
#                - java.io.IOException
#            ignoreExceptions:
#                - io.github.robwin.exception.BusinessException
#                
#            
#        
#resilience4j.ratelimiter:
#    instances:
#        backendA:
#            limitForPeriod: 10
#            limitRefreshPeriod: 1s
#            timeoutDuration: 0
#            registerHealthIndicator: true
#            eventConsumerBufferSize: 100
#        backendB:
#            limitForPeriod: 6
#            limitRefreshPeriod: 500ms
#            timeoutDuration: 3s