server:
  port: 8002
  
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8003/eureka/"
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update